server:
  port: 2104
spring:
  application:
    name: cards-consultation
#logging.level.org.lfenergy.operatorfabric: debug
#here we put urls for all feign clients
users:
  ribbon:
    listOfServers: http://localhost:2103
