server:
  port: 2103

spring:
  application:
    name: users


operatorfabric.users.default:
  users:
    - login: admin
      groupSet: [ADMIN]
    - login: admin
      groups: ["ADMIN"]
      entities: ["ENTITY1","ENTITY2"]
    - login: operator3
      groups: ["RTE","ADMIN","ReadOnly","Dispatcher"]
      entities: ["ENTITY1"]
    - login: operator1-admin
      groups: ["Dispatcher","ReadOnly","ADMIN"]
      entities: ["ENTITY1"]
    - login: operator1
      groups: ["Dispatcher","ReadOnly"]
      entities: ["ENTITY1"]
    - login: operator2
      groups: ["Planner", "ReadOnly"]
      entities: ["ENTITY2"]
  groups:
    - id: ADMIN
      name: ADMINISTRATORS
      description: The admin group
    - id: RTE
      name: RTE France
      description: RTE TSO Group
    - id: Dispatcher
      name: Dispatcher
      description: Dispatcher Group
    - id: Planner
      name: Planner
      description: Planner Group
    - id: Supervisor
      name: Supervisor
      description: Supervisor Group
    - id: Manager
      name: Manager
      description: Manager Group
    - id: ReadOnly
      name: ReadOnly
      description: ReadOnly Group
  entities:
    - id: ENTITY1
      name: Control Room 1
      description: Control Room 1
    - id: ENTITY2
      name: Control Room 2
      description: Control Room 2
    - id: ENTITY3
      name: Control Room 3
      description: Control Room 3
    - id: ENTITY4
      name: Control Room 4
      description: Control Room 4
  user-settings:
    - login: operator3
      description: Da Operator Rulez
#logging:
#  level:
#    ROOT: DEBUG